create table if not exists public.real2free_viewer_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  created_at timestamptz not null default now(),
  visitor_hash text not null,
  session_hash text not null,
  user_agent_hash text,
  event_type text not null check (event_type in ('engaged_visit','play_clicked','player_started','watch_30s','watch_2m')),
  path text not null,
  title_label text,
  referrer_host text,
  country text,
  device text not null check (device in ('mobile','tablet','desktop','unknown')),
  source_kind text not null check (source_kind in ('video','embed','external','unknown')),
  verification text not null check (verification in ('interaction','media_playback','media_time','embed_loaded','embed_visible','external_click','unknown')),
  likely_bot boolean not null default false
);

create index if not exists real2free_viewer_events_event_created_idx
  on public.real2free_viewer_events (event_type, created_at desc);
create index if not exists real2free_viewer_events_session_created_idx
  on public.real2free_viewer_events (session_hash, created_at desc);

alter table public.real2free_viewer_events enable row level security;
revoke all on table public.real2free_viewer_events from anon, authenticated;
revoke all on sequence public.real2free_viewer_events_id_seq from anon, authenticated;
